version: '3'

services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: jason
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: django_blog
    volumes:
    - /home/jason/workspace/code/DockerVolume/django_blog/MySQL/data:/var/lib/mysql
    - ./compose/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
    - "3306:3306"
    expose:
    - "3306"

  redis:
    image: redis:4.0
    command: redis-server --requirepass 123
    ports:
    - '6379:6379'
    expose:
    - "6379"
    volumes:
    - /home/jason/workspace/code/DockerVolume/django_blog/Redis/data:/data
    env_file: .envs/.env

  django:
    image: base-django:1.0
    command: /start-dev.sh
    depends_on:
    - redis
    - mysql
    volumes:
    - .:/webapp
    ports:
    - "5000:5000"
    env_file: .envs/.env
    stdin_open: true
    tty: true

  rabbitmq:
    image: rabbitmq:3.6.7
    env_file: .envs/.env
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"

  celeryworker:
    image: base-django:1.0
    command: /start-celeryworker.sh
    depends_on:
    - redis
    volumes:
    - .:/webapp
    env_file: .envs/.env

  pycharm:
    image: base-django:1.0
    depends_on:
    - rabbitmq
    - redis
    - mysql
    volumes:
    - .:/webapp
    env_file: .envs/.env

  celeryflower:
    image: base-django:1.0
    command: /start-celeryflower.sh
    volumes:
    - .:/webapp
    depends_on:
    - rabbitmq
    - redis
    env_file: .envs/.env
    ports:
    - "5555:5555"
