version: '3'

services:
  mysql:
    image: mysql:5.7
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/db_data:/var/lib/mysql
    #      - ./compose/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: django_blog
      MYSQL_USER: jason
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    expose:
      - "3306"

  redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass 123
      '
    ]
    volumes:
      - /var/lib/redis_data:/data
    environment:
      REDIS_PASS_FILE: /run/secrets/redis-password
    ports:
      - '6379:6379'
    expose:
      - "6379"

  web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - mysql
      - redis
    env_file:
      - .envs/.env

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-celeryworker.sh
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/code
    env_file:
      - .envs/.env
