version: '3'

services:
  mysql:
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_ROOT_PASSWORD 123
    - MYSQL_USER jason
    - MYSQL_PASSWORD 123
    - MYSQL_DATABASE django_blog
    volumes:
    - /home/jason/workspace/code/DockerVolume/django_blog/MySQL/data:/var/lib/mysql
    - ./compose/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
    - "3306:3306"
    expose:
    - "3306"

  redis:
    image: redis:3.2.0
    command: redis-server --requirepass 123
    ports:
    - '6379:6379'
    expose:
    - "6379"
    volumes:
    - /home/jason/workspace/code/DockerVolume/django_blog/Redis/data:/data
    env_file: .envs/.env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /start-dev.sh
    depends_on:
    - redis
    - mysql
    volumes:
    - .:/webapp
    ports:
    - "8000:8000"
    env_file: .envs/.env
    stdin_open: true
    tty: true
