version: '3'

volumes:
  production_mysql_data: {}
  production_redis_data: {}


services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: jason
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: django_blog
    volumes:
    - production_mysql_data:/var/lib/mysql
    - ./compose/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
    - "3306:3306"
    expose:
    - "3306"

  redis:
    image: redis:4.0
    command: redis-server --requirepass 123
    ports:
    - '6379:6379'
    expose:
    - "6379"
    volumes:
    - production_redis_data:/data
    env_file: .envs/.env

  rabbitmq:
    image: rabbitmq:3.6.7
    env_file: .envs/.env
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"